server:
  port: 8090
  servlet:
    # context-path就是端口号与服务之间要加的一段路径，比如localhost:8080/wcm/login/login的/wcm就是
    context-path: /material

spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/material_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#Redis配置
redis:
  port: 6379
  host: 127.0.0.1
  password: redis@2hefei-1haohan
  maxIdle: 0
  minIdle: 200
  timeout: 60000


mybatis:
  # 加载配置文件
  mapper-locations: classpath*:sqlmap/*.xml
  # 实体类所在路径，填写改路径mapper文件中可以不写全路径
  type-aliases-package: com.amx.material
  configuration:
    #下划线转驼峰
    map-underscore-to-camel-case: true